# Generated by Django 4.2.4 on 2023-08-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_trainer', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=10)),
                ('course_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=50)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutent_app.course')),
            ],
        ),
    ]
